# Generated by Django 6.0 on 2026-01-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': '"User"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developerId', models.AutoField(db_column='developerid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'developer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightId', models.AutoField(db_column='flightid', primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departureTime', models.DateTimeField(db_column='departuretime')),
                ('arrivalTime', models.DateTimeField(db_column='arrivaltime')),
            ],
            options={
                'db_table': 'flight',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(db_column='bookingid', primary_key=True, serialize=False)),
                ('bookingDate', models.DateTimeField(db_column='bookingdate')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='core.appuser')),
                ('flight', models.ForeignKey(db_column='flightid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.flight')),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('policyId', models.AutoField(db_column='policyid', primary_key=True, serialize=False)),
                ('coverageAmount', models.DecimalField(db_column='coverageamount', decimal_places=2, max_digits=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(db_column='bookingid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.booking')),
            ],
            options={
                'db_table': 'insurancepolicy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('claimId', models.AutoField(db_column='claimid', primary_key=True, serialize=False)),
                ('delayDuration', models.FloatField(db_column='delayduration')),
                ('claimStatus', models.CharField(db_column='claimstatus', max_length=50)),
                ('payoutAmount', models.DecimalField(db_column='payoutamount', decimal_places=2, max_digits=10)),
                ('policy', models.ForeignKey(db_column='policyid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.insurancepolicy')),
            ],
            options={
                'db_table': 'insuranceclaim',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusLookup',
            fields=[
                ('statusId', models.AutoField(db_column='statusid', primary_key=True, serialize=False)),
                ('statusType', models.CharField(db_column='statustype', max_length=20)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'statuslookup',
                'managed': True,
                'unique_together': {('statusType', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(db_column='paymentid', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(db_column='paymentmethod', max_length=50)),
                ('paymentDate', models.DateTimeField(db_column='paymentdate')),
                ('booking', models.ForeignKey(db_column='bookingid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.booking')),
                ('status', models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.statuslookup')),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='status',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.statuslookup'),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.statuslookup'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.statuslookup'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.AutoField(db_column='ticketid', primary_key=True, serialize=False)),
                ('seatNumber', models.CharField(db_column='seatnumber', max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issueDate', models.DateTimeField(db_column='issuedate')),
                ('isPremium', models.BooleanField(db_column='ispremium', default=False)),
                ('booking', models.ForeignKey(db_column='bookingid', on_delete=django.db.models.deletion.DO_NOTHING, to='core.booking')),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
    ]
