# Generated by Django 6.0 on 2026-01-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='blockchainPolicyId',
            field=models.IntegerField(blank=True, db_column='blockchainpolicyid', null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='blockchainTxHash',
            field=models.CharField(blank=True, db_column='blockchaintxhash', max_length=66, null=True),
        ),
    ]
