# Generated by Django 6.0 on 2026-01-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_blockchain_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.CASCADE, to='core.statuslookup'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.appuser'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.CASCADE, to='core.statuslookup'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='booking',
            field=models.ForeignKey(db_column='bookingid', on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
        ),
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.CASCADE, to='core.statuslookup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(db_column='bookingid', on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.CASCADE, to='core.statuslookup'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(db_column='bookingid', on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
        ),
    ]
