# Generated by Django 6.0 on 2026-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cascade_delete_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslookup',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
